### ISSUE TITLE
反射加载的类会报错Caused by: java.lang.ClassNotFoundException:找不到类，怎么解决

### ISSUE THREAD

**Issue by pengguojin** [xautlx/package-optimize-demo#2]
反射加载的类会报错Caused by: java.lang.ClassNotFoundException:找不到类，怎么解决

**Comment by xautlx** [comment]
是源工程运行报错吗还是做了什么调整？请补充给详细错误描述和异常堆栈

**Comment by pengguojin** [comment]
我使用了shardingsphere，项目在idea能正常启动，项目启动的时候会加载com.smc.sharding.MyComplexShardingAlgorithm

![image](https://user-images.githubusercontent.com/28942458/117913935-e35a5d00-b314-11eb-9bd7-0750dda2c531.png)

我查看源码，如上图，使用了Class<?> result = Class.forName(shardingAlgorithmClassName);会报下面找不到class的错，但我查看打包后的jar包这个class是存在的

```java
Caused by: java.lang.ClassNotFoundException: com.smc.sharding.MyComplexShardingAlgorithm
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:315)
        at org.apache.shardingsphere.core.strategy.route.ShardingAlgorithmFactory.newInstance(ShardingAlgorithmFactory.java:43)
        at org.apache.shardingsphere.core.yaml.swapper.ShardingStrategyConfigurationYamlSwapper.swap(ShardingStrategyConfigurationYamlSwapper.java:84)
        at org.apache.shardingsphere.core.yaml.swapper.TableRuleConfigurationYamlSwapper.swap(TableRuleConfigurationYamlSwapper.java:59)
        at org.apache.shardingsphere.core.yaml.swapper.ShardingRuleConfigurationYamlSwapper.swap(ShardingRuleConfigurationYamlSwapper.java:81)
        at org.apache.shardingsphere.shardingjdbc.spring.boot.SpringBootConfiguration.shardingDataSource(SpringBootConfiguration.java:103)
        at org.apache.shardingsphere.shardingjdbc.spring.boot.SpringBootConfiguration$$EnhancerBySpringCGLIB$$3a5f10f7.CGLIB$shardingDataSource$3(<generated>)
        at org.apache.shardingsphere.shardingjdbc.spring.boot.SpringBootConfiguration$$EnhancerBySpringCGLIB$$3a5f10f7$$FastClassBySpringCGLIB$$bc7e6294.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
        at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
        at org.apache.shardingsphere.shardingjdbc.spring.boot.SpringBootConfiguration$$EnhancerBySpringCGLIB$$3a5f10f7.shardingDataSource(<generated>)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
        ... 58 common frames omitted
```

**Comment by pengguojin** [comment]
我使用了shardingsphere，项目在idea能正常启动，项目启动的时候会加载com.smc.sharding.MyComplexShardingAlgorithm
然后我按照你第二种方法打包后，jar -jar启动会报错，如下

```java
Caused by: java.lang.ClassNotFoundException: com.smc.sharding.MyComplexShardingAlgorithm
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:315)
        at org.apache.shardingsphere.core.strategy.route.ShardingAlgorithmFactory.newInstance(ShardingAlgorithmFactory.java:43)
        at org.apache.shardingsphere.core.yaml.swapper.ShardingStrategyConfigurationYamlSwapper.swap(ShardingStrategyConfigurationYamlSwapper.java:84)
        at org.apache.shardingsphere.core.yaml.swapper.TableRuleConfigurationYamlSwapper.swap(TableRuleConfigurationYamlSwapper.java:59)
        at org.apache.shardingsphere.core.yaml.swapper.ShardingRuleConfigurationYamlSwapper.swap(ShardingRuleConfigurationYamlSwapper.java:81)
        at org.apache.shardingsphere.shardingjdbc.spring.boot.SpringBootConfiguration.shardingDataSource(SpringBootConfiguration.java:103)
        at org.apache.shardingsphere.shardingjdbc.spring.boot.SpringBootConfiguration$$EnhancerBySpringCGLIB$$3a5f10f7.CGLIB$shardingDataSource$3(<generated>)
        at org.apache.shardingsphere.shardingjdbc.spring.boot.SpringBootConfiguration$$EnhancerBySpringCGLIB$$3a5f10f7$$FastClassBySpringCGLIB$$bc7e6294.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
        at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
        at org.apache.shardingsphere.shardingjdbc.spring.boot.SpringBootConfiguration$$EnhancerBySpringCGLIB$$3a5f10f7.shardingDataSource(<generated>)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
        ... 58 common frames omitted
```

然后我查看源码，如下图，使用了Class<?> result = Class.forName(shardingAlgorithmClassName);
会报下面找不到class的错，但我查看打包后的jar包，这个class是存在的
![image](https://user-images.githubusercontent.com/28942458/117913935-e35a5d00-b314-11eb-9bd7-0750dda2c531.png)

**Comment by xautlx** [comment]
由于-Djava.ext.dirs参数是按照ext class loader来加载的，一般的java程序是使用app class loader来加载代码的。建议试试文章后续的打包加载方式。
